### ISSUE TITLE
Support non-integer primary keys in the generic foreign key

### ISSUE THREAD

**Issue by holms** [maykinmedia/django-timeline-logger#7]
According to your tests this should not be an issue:

```
        TimelineLog.log_from_request(
            request,
            Application.objects.get(application_id=request.GET['id']),
            'timeline_logger/application_submitted.txt'
        )
```

And it complains something about user

```
    trigger_log()
  File "/source/application/views.py", line 3736, in trigger_log
    'timeline_logger/application_submitted.txt'
  File "/usr/local/lib/python3.5/site-packages/timeline_logger/models.py", line 68, in log_from_request
    user=user,
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 555, in __init__
    _setattr(self, field.name, rel_obj)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 216, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fdd3e49be48>>": "TimelineLog.user" must be a "User" instance.

```

What does it searching for?

**Comment by sergei-maertens** [comment]
Looking at the traceback, the user you're trying to assign is not logged in. `django.contrib.auth.models.AnonymousUser` is not a model class, so it cannot possibly be used as the value for the `ForeignKey`.

I think you need to either ensure the user is logged in, or drop down a little bit more low-level than `log_from_request` and specify the user yourself as `request.user if request.user.is_authenticated else None`.

edit: with low level I mean the approach documented at http://django-timeline-logger.readthedocs.io/en/latest/usage.html#default-example

**Comment by holms** [comment]
@sergei-maertens that's exactly what I want to log without user, we don't use users in here in this project. Trying your variant now got different error hope it's not related to user. would be grateful for the hints:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/source/application/views.py", line 3757, in payment_confirmation
    trigger_log()
  File "/source/application/views.py", line 3737, in trigger_log
    'timeline_logger/application_submitted.txt',
  File "/usr/local/lib/python3.5/site-packages/timeline_logger/models.py", line 68, in log_from_request
    user=user,
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range

```

Just defined `request.user = None` before timelogger request logging

**Comment by holms** [comment]
Ok this is solved it was a that object field, it want pk as integer from another object. but there's more surprises: 

```
  File "/source/application/views.py", line 3737, in trigger_log
    'timeline_logger/application_submitted.txt',
  File "/usr/local/lib/python3.5/site-packages/timeline_logger/models.py", line 68, in log_from_request
    user=user,
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'content_object' is an invalid keyword argument for this function

```
```
root@6a60ac5c3323:/source# cat application/templates/timeline_logger/application_submitted.txt 
{% load i18n %}
{% blocktrans trimmed with timestamp=log.timestamp object=log.content_object extra=log.exta_data|safe %}
   {{ timestamp }} - Applicant submitted application "{{ object }}"
{% endblocktrans %}
```

complains for that `log.content_object`
update: even removing it from template it complains.

For the item part it's like this:
```
Application.objects.get(application_id=request.GET['id']).pk,
```

Update: Tried also this one - no go:
```
     item = Application.objects.get(
            pk=Application.objects.get(application_id=request.GET['id']).pk
        )
```

**Comment by sergei-maertens** [comment]
@holms can you paste the `trigger_log()` function?

**Comment by holms** [comment]
@sergei-maertens sorry for not posting it properly.

It's inside that particular view so it follows like this:

```
def trigger_log():
    item = Application.objects.get(application_id=request.GET['id'])
    TimelineLog.objects.create(
            content_object=item,
            user=None
    )
```

This produces same result as this:

```
def trigger_log():
    item = Application.objects.get(application_id=request.GET['id'])
    TimelineLog.log_from_request(
           request,
           item,
          'time_logger/somefile.txt'
     )

```

It's because of that particular key, are foreign key not allowed to be UUID? Because that error looks like complains that PK is not integer..?

**Comment by sergei-maertens** [comment]
Ah, that explains! Currently the model only supports integer 'ForeignKey', yes, see https://github.com/maykinmedia/django-timeline-logger/blob/develop/timeline_logger/models.py#L23

Our original use case for this library favoured `IntegerField` over `TextField` (which would work for you) because of performance reasons

**Comment by holms** [comment]
oh snap, do you think it's possible to extend timelogger model and just override that part?

**Comment by sergei-maertens** [comment]
Unfortunately you can't override model fields via inheritance in Django. I think I'd suggest forking this library and changing the model to your liking, or looking into other solutions :(

**Comment by holms** [comment]
@sergei-maertens seems to be it's possible in Django 1.10

Here's example:

```
class Place(models.Model):
    name = models.CharField(max_length=20)
    rating = models.DecimalField()

    class Meta:
        abstract = True

class LongNamedRestaurant(Place):  # Subclassing `Place`.
    name = models.CharField(max_length=255)  # Notice, I'm overriding `Place.name` to give it a longer length.
    food_type = models.CharField(max_length=25)
```

You need to make that model an abstract class.
https://docs.djangoproject.com/en/2.0/topics/db/models/#field-name-hiding-is-not-permitted

**Comment by sergei-maertens** [comment]
I wasn't aware of that, but having to make the model abstract will break other usages of this package since now you have you provide your own concrete model... I'll have to discuss with a couple people if we want to support this or not.

**Comment by holms** [comment]
Ticket name can be changed  if we're solving this issue. I'd vote more to go with TextField() as then you wouldn't have to refactor anything. Had to edit also init migration file btw. Seems to be working on my fork. With that abstract method admin breaks too.

**Comment by sergei-maertens** [comment]
I've updated the title, still need to discuss internally!

**Comment by sergei-maertens** [comment]
@holms took a ocuple days to get back to this, but we don't have any blocking arguments anymore, so soon we'll be making the `object_id` field a `TextField` instead. This or next week we'll probably have a new version on PyPI.

**Comment by sergei-maertens** [comment]
See #9 for the progress on this

**Comment by holms** [comment]
So grateful! :)

**Comment by sergei-maertens** [comment]
@holms `django-timeline-logger==1.0` is now on PyPI

**Comment by holms** [comment]
Thank you for your help :)
